# This is a basic workflow to help you get started with Actions
name: Testing GitVersion

# Controls when the action will run.
on:
  #Trigger the workflow on merging a pull request to master branch
  pull_request:
#    branches: [main]
    types: [closed, synchronize, opened]
  # Triggers the workflow on push or pull request events but only for the workflow branch
#  push:
#    branches: [ Setup-Workflow ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BROKER_HOSTNAME: ${{ secrets.BROKER_HOSTNAME }}

jobs:
  merge-successful:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Create Build Label
        run: echo $CURRENT_BUILD
        env:
          CURRENT_BUILD: ${{steps.gitversion.outputs.major}}.${{steps.gitversion.outputs.minor}}.${GITHUB_HEAD_REF##*/}.${{steps.gitversion.outputs.buildMetaData}}

  waiting-to-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Create release
        run: echo $CURRENT_BUILD
        env:
          CURRENT_BUILD: ${{steps.gitversion.outputs.major}}.${{steps.gitversion.outputs.minor}}.${GITHUB_HEAD_REF##*/}.${{steps.gitversion.outputs.buildMetaData}}
